#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.2 on Fri Jan 12 13:38:18 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "URL of Playlist to Import")
        self.text_url = wx.TextCtrl(self, wx.ID_ANY, "")
        self.radio_btn_prefix = wx.RadioButton(self, wx.ID_ANY, "Use the name from the imported playlist name")
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "Prefix:")
        self.text_prefix = wx.TextCtrl(self, wx.ID_ANY, "")
        self.radio_btn_new_name = wx.RadioButton(self, wx.ID_ANY, "Use a new playlist name")
        self.text_playlist_name = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_load = wx.Button(self, wx.ID_ANY, "Load")
        self.label_load_result = wx.StaticText(self, wx.ID_ANY, "\n")
        self.button_import = wx.Button(self, wx.ID_ANY, "Import")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.text_url_change, self.text_url)
        self.Bind(wx.EVT_RADIOBUTTON, self.radio_btn_change, self.radio_btn_prefix)
        self.Bind(wx.EVT_TEXT, self.text_prefix_change, self.text_prefix)
        self.Bind(wx.EVT_RADIOBUTTON, self.radio_btn_change, self.radio_btn_new_name)
        self.Bind(wx.EVT_TEXT, self.text_playlist_name_change, self.text_playlist_name)
        self.Bind(wx.EVT_BUTTON, self.button_load_click, self.button_load)
        self.Bind(wx.EVT_BUTTON, self.button_import_click, self.button_import)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("spotify_playlist_apple_music")
        self.SetSize((723, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.label_1, 0, 0, 0)
        sizer_2.Add(self.text_url, 0, wx.EXPAND, 0)
        sizer_2.Add(self.radio_btn_prefix, 0, 0, 0)
        sizer_3.Add(self.label_2, 0, 0, 0)
        sizer_3.Add(self.text_prefix, 1, 0, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.radio_btn_new_name, 0, 0, 0)
        sizer_2.Add(self.text_playlist_name, 0, wx.EXPAND, 0)
        sizer_2.Add(self.button_load, 0, 0, 0)
        sizer_2.Add(self.label_load_result, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.button_import, 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def text_url_change(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'text_url_change' not implemented!"
        event.Skip()

    def radio_btn_change(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'radio_btn_change' not implemented!"
        event.Skip()

    def text_prefix_change(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'text_prefix_change' not implemented!"
        event.Skip()

    def text_playlist_name_change(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'text_playlist_name_change' not implemented!"
        event.Skip()

    def button_load_click(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'button_load_click' not implemented!"
        event.Skip()

    def button_import_click(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'button_import_click' not implemented!"
        event.Skip()

# end of class MyFrame
